services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: days_battery_php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DATABASE_URL: postgresql://app:secret@postgres:5432/days_battery?serverVersion=16&charset=utf8
      REDIS_URL: redis://redis:6379
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-changeme}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: days_battery_nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: days_battery_postgres
    environment:
      POSTGRES_DB: days_battery
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: days_battery_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
