controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

battery_controllers:
    resource:
        path: ../src/Battery/Presentation/Controller/
        namespace: App\Battery\Presentation\Controller
    type: attribute
